name: Daily insider scan

on:
  schedule:
    # ~21:30 Israel ≈ 19:30 UTC (adjust for DST if you want)
    - cron: "30 19 * * *"
  workflow_dispatch: {}

jobs:
  scan:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install -r requirements.txt
      - name: Run scanner
        env:
          SEC_EMAIL: ${{ secrets.SEC_EMAIL }}
        run: |
          python insider_scanner.py --days 14 --min_owners 3 --min_usd 300000 | tee insider.log
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: insider_outputs
          path: |
            insider_trades.csv
            alerts.csv
            insider.log
          if-no-files-found: warn
